// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestourantServiceApp.DataAccsessLayer.Contexts;

#nullable disable

namespace RestourantServiceApp.DataAccsessLayer.Migrations
{
    [DbContext(typeof(RestourantDbContext))]
    [Migration("20260324090042_mig_seeds")]
    partial class mig_seeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestourantServiceApp.Core.Models.MenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MenuItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b3b5e5c3-2f1a-4c8f-9c1a-0b6b1f3a1a01"),
                            Category = 4,
                            Name = "Margherita Pizza",
                            Price = 12.50m
                        },
                        new
                        {
                            Id = new Guid("c4c6f6d4-3a2b-4d9f-a2b3-1c7c2f4b2b02"),
                            Category = 5,
                            Name = "Cheeseburger",
                            Price = 10.00m
                        },
                        new
                        {
                            Id = new Guid("d5d7f7e5-4b3c-5e1f-b3c4-2d8d3f5c3c03"),
                            Category = 2,
                            Name = "Caesar Salad",
                            Price = 8.75m
                        },
                        new
                        {
                            Id = new Guid("e6e8f8f6-5c4d-6f2f-c4d5-3e9e4f6d4d04"),
                            Category = 6,
                            Name = "Grilled Salmon",
                            Price = 18.90m
                        },
                        new
                        {
                            Id = new Guid("f7f9f9f7-6d5e-7a3f-d5e6-4f1f5f7e5e05"),
                            Category = 3,
                            Name = "Spaghetti Bolognese",
                            Price = 13.40m
                        },
                        new
                        {
                            Id = new Guid("a8a1a1f8-7e6f-8b4f-e6f7-5a2a6a8f6f06"),
                            Category = 10,
                            Name = "Chicken Nuggets",
                            Price = 7.20m
                        },
                        new
                        {
                            Id = new Guid("a9b2c3d4-8f7e-9c5d-f7e8-6b3b7a9d7d07"),
                            Category = 13,
                            Name = "Chocolate Cake",
                            Price = 6.50m
                        },
                        new
                        {
                            Id = new Guid("b1c2d3e4-9a8b-1d6e-e8b9-7c4c8b1e8e08"),
                            Category = 15,
                            Name = "Latte",
                            Price = 4.30m
                        });
                });

            modelBuilder.Entity("RestourantServiceApp.Core.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Date = new DateTime(2026, 3, 22, 13, 0, 41, 597, DateTimeKind.Local).AddTicks(5937),
                            TotalAmount = 35.00m
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Date = new DateTime(2026, 3, 23, 13, 0, 41, 597, DateTimeKind.Local).AddTicks(5959),
                            TotalAmount = 27.65m
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Date = new DateTime(2026, 3, 24, 13, 0, 41, 597, DateTimeKind.Local).AddTicks(5961),
                            TotalAmount = 76.20m
                        });
                });

            modelBuilder.Entity("RestourantServiceApp.Core.Models.OrderItem", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MenuItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "MenuItemId");

                    b.HasIndex("MenuItemId")
                        .IsUnique();

                    b.ToTable("OrderItems", (string)null);

                    b.HasData(
                        new
                        {
                            OrderId = new Guid("11111111-1111-1111-1111-111111111111"),
                            MenuItemId = new Guid("b3b5e5c3-2f1a-4c8f-9c1a-0b6b1f3a1a01"),
                            Count = 2
                        },
                        new
                        {
                            OrderId = new Guid("11111111-1111-1111-1111-111111111111"),
                            MenuItemId = new Guid("c4c6f6d4-3a2b-4d9f-a2b3-1c7c2f4b2b02"),
                            Count = 1
                        },
                        new
                        {
                            OrderId = new Guid("22222222-2222-2222-2222-222222222222"),
                            MenuItemId = new Guid("d5d7f7e5-4b3c-5e1f-b3c4-2d8d3f5c3c03"),
                            Count = 1
                        },
                        new
                        {
                            OrderId = new Guid("22222222-2222-2222-2222-222222222222"),
                            MenuItemId = new Guid("e6e8f8f6-5c4d-6f2f-c4d5-3e9e4f6d4d04"),
                            Count = 1
                        },
                        new
                        {
                            OrderId = new Guid("33333333-3333-3333-3333-333333333333"),
                            MenuItemId = new Guid("f7f9f9f7-6d5e-7a3f-d5e6-4f1f5f7e5e05"),
                            Count = 3
                        },
                        new
                        {
                            OrderId = new Guid("33333333-3333-3333-3333-333333333333"),
                            MenuItemId = new Guid("a8a1a1f8-7e6f-8b4f-e6f7-5a2a6a8f6f06"),
                            Count = 2
                        },
                        new
                        {
                            OrderId = new Guid("33333333-3333-3333-3333-333333333333"),
                            MenuItemId = new Guid("a9b2c3d4-8f7e-9c5d-f7e8-6b3b7a9d7d07"),
                            Count = 2
                        },
                        new
                        {
                            OrderId = new Guid("33333333-3333-3333-3333-333333333333"),
                            MenuItemId = new Guid("b1c2d3e4-9a8b-1d6e-e8b9-7c4c8b1e8e08"),
                            Count = 2
                        });
                });

            modelBuilder.Entity("RestourantServiceApp.Core.Models.OrderItem", b =>
                {
                    b.HasOne("RestourantServiceApp.Core.Models.MenuItem", "MenuItem")
                        .WithOne("OrderItem")
                        .HasForeignKey("RestourantServiceApp.Core.Models.OrderItem", "MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestourantServiceApp.Core.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RestourantServiceApp.Core.Models.MenuItem", b =>
                {
                    b.Navigation("OrderItem")
                        .IsRequired();
                });

            modelBuilder.Entity("RestourantServiceApp.Core.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
